/* eslint-disable @next/next/no-img-element */
"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "BestArt Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isMenuMobileOpen, setIsMenuMobileOpen] = useState(false);
  return (
    <html lang="en">
      <head>
        <title>BestArt Design</title>
      </head>
      <body className={inter.className}>
        <header className="fixed top-0 right-0 left-0 max-h-scree">
          <div className="py-6 px-4 flex justify-between bg-white max-h-20">
            <Link href="/">
              <img
                className="w-full object-cover max-w-28"
                src="https://assets-global.website-files.com/63d0f93b8842ec945ab130c6/64185cc31e8137d828ab7613_img-logo-sibambo.png"
                alt="logo-header"
              />
            </Link>
            <span
              className="material-icons material-icons-outlined"
              onClick={() => setIsMenuMobileOpen(!isMenuMobileOpen)}
            >
              drag_handle
            </span>
          </div>

          {isMenuMobileOpen && (
            <div className="h-screen flex flex-col items-end gap-7 pt-10 text-3xl backdrop-blur-md px-4">
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/"
              >
                Home
              </Link>
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/proyek"
              >
                Proyek
              </Link>
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/blog"
              >
                Blog
              </Link>
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/tentang-kami"
              >
                Tentang Kami
              </Link>
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/paket-harga"
              >
                Paket Harga
              </Link>
              <Link
                onClick={() => setIsMenuMobileOpen(false)}
                className="text-shadow"
                href="/hubungi-kami"
              >
                Hubungi Kami
              </Link>
            </div>
          )}
        </header>

        <main className="mt-20 min-h-screen">{children}</main>

        <footer className="mt-20">
          <div className="aspect-[5/3] relative">
            <img
              className="w-full h-full object-cover"
              src="https://assets-global.website-files.com/63d0f93b8842ec945ab130c6/642865468fbcbe36efc5769b_img-bg_banner.webp"
              alt="logo-header"
            />
            <div className="absolute top-0 left-0 right-0 bottom-0 text-white ">
              <div className="flex flex-col gap-7 py-5 px-4">
                <h3 className="uppercase text-4xl text-center font-medium">
                  Setiap Rumah <br /> punya cerita
                </h3>
                <div className="border rounded-full py-5 text-xl uppercase flex items-center justify-center gap-5">
                  <i className="material-icons">arrow_forward</i>
                  {/* icon right */}
                  <span>Hubungi Kami</span>
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-7 mt-20 px-4">
            <Link href="/">
              <img
                className="w-full object-cover max-w-28"
                src="https://assets-global.website-files.com/63d0f93b8842ec945ab130c6/64185cc31e8137d828ab7613_img-logo-sibambo.png"
                alt="logo-header"
              />
            </Link>
            <p>
              Setiap rumah punya cerita. Kami memahami bahwa setiap orang
              berbeda. Karenanya, kami merancang rumah yang sesuai dengan
              karakter Anda masing-masing, sebagaimana setiap rumah punya cerita
              sendiri
            </p>

            <div className="flex flex-col">
              <span className="font-bold">SURABAYA</span>
              <span>Jl. Raya Darmo Permai III No. 28</span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold">Jakarta</span>
              <span>
                Komplek Warnet Pandu (Depan Apartment Parkland Avenue, Jl. Raya
                Serpong No.99, RT.11/RW.04, Cilenggang, Kec. Serpong, Kota
                Tangerang Selatan, Banten 15311
              </span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold">EMAIL ADDRESS</span>
              <span>
                <a href="mailto:admin@bestartdesign.com">
                  admin@bestartdesign.com
                </a>
              </span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold">PHONE NUMBER</span>
              <span>
                <a href="tel:081xxxxxxx">0812xxxxxxx</a>
                </span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold">SOCIAL MEDIA</span>
              <span>Instagram</span>
              <span>TikTok</span>
              <span>LinkedIn</span>
              <span>Youtube</span>
            </div>
          </div>
          <div className="mt-5 bg-gray-50">
            <p className="text-center">
              © 2021 BestArt Design. All rights reserved
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
